//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dbl
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string address { get; set; }
        public System.DateTime dateOfBirth { get; set; }
        public int phone { get; set; }
        public Nullable<int> mobilePhone { get; set; }
        public int idMember { get; set; }
    
        public virtual coronaDetails coronaDetails { get; set; }
    }
}
